name: Deploy

on:
  release:
    types: [published]

env:
  DCL_PRIVATE_KEY: ${{ secrets.DCL_WORLDS_PRIVATE_KEY }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    name: Deploy to .org
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install npm packages
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
    - name: Build scene
      run: |
        npm install --no-save @dcl/sdk@auth-server @dcl/js-runtime@7.21.1-22918726402.commit-ee210ee
        npm run build
    - name: Deploy scene
      run: npm run deploy:production
